# Generated by Django 5.2.7 on 2025-10-05 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_index=True, max_length=255, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipper_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Company Name')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Contact Name')),
                ('contact_title', models.CharField(blank=True, max_length=100, verbose_name='Contact Title')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Order Date')),
                ('required_date', models.DateTimeField(blank=True, null=True, verbose_name='Required Date')),
                ('shipped_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Shipped Date')),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Freight')),
                ('ship_name', models.CharField(blank=True, max_length=255, verbose_name='Ship Name')),
                ('ship_address', models.CharField(blank=True, max_length=255, verbose_name='Ship Address')),
                ('ship_city', models.CharField(blank=True, max_length=100, verbose_name='Ship City')),
                ('ship_region', models.CharField(blank=True, max_length=100, verbose_name='Ship Region')),
                ('ship_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Ship Postal Code')),
                ('ship_country', models.CharField(blank=True, max_length=100, verbose_name='Ship Country')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.employee', verbose_name='Employee')),
                ('ship_via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='northwind.shipper', verbose_name='Ship Via')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-orderdate'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_index=True, max_length=255, verbose_name='Product Name')),
                ('quantity_per_unit', models.CharField(blank=True, max_length=100, verbose_name='Quantity Per Unit')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price')),
                ('units_in_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Units In Stock')),
                ('units_on_order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Units On Order')),
                ('reorder_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reorder Level')),
                ('discontinued', models.BooleanField(default=False, verbose_name='Discontinued')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='northwind.category', verbose_name='Category')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='northwind.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='northwind.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='northwind.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'order_detail',
                'indexes': [models.Index(fields=['order', 'product'], name='order_detai_order_i_88295a_idx')],
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-orderdate'], name='northwind_o_orderda_b6264d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-orderdate'], name='northwind_o_custome_00bf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipped_date'], name='northwind_o_shipped_031aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='northwind_p_product_58657e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'discontinued'], name='northwind_p_categor_a9a13e_idx'),
        ),
    ]
