# Generated by Django 5.2.7 on 2025-10-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='northwinduser',
            name='user_type',
            field=models.CharField(choices=[('CUS', 'Customer'), ('EMP', 'Employee')], default='CUS', max_length=3),
        ),
    ]
