# Generated by Django 5.2.7 on 2025-10-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_northwinduser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='northwinduser',
            name='user_type',
            field=models.CharField(choices=[('CUS', 'Customer'), ('EMP', 'Employee'), ('ADM', 'Administrator')], default='CUS', max_length=3),
        ),
    ]
