# Generated by Django 5.2.7 on 2025-10-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='northwinduser',
            name='custom_id',
        ),
    ]
